"""Add review tablegame

Revision ID: ccd9972ff511
Revises: cdf92ec936ca
Create Date: 2023-09-06 20:40:01.913655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd9972ff511'
down_revision = 'cdf92ec936ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
